### ISSUE TITLE
mention nmap 7.0+ required

### ISSUE THREAD

**Issue by carnal0wnage** [averagesecurityguy/ptnotes#2]
Might just want to mention nmap 7.+ ?? is required  i had an old version of nmap 6.40 that was not adding the <!DOCTYPE nmaprun> to the xml output.  took me a bit to figure out why some scans would import and others wouldnt :-)  

also just adding that line to the top of the xml file will make it import

also might be a design decision but can we also push the the error log to the console running the server?

**Comment by averagesecurityguy** [comment]
Import should support older Nmap XML files now. In addition, logging errors to both console and log file. https://github.com/averagesecurityguy/ptnotes/releases/tag/v1.0.1
